import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/main_apps/components/globals/navbars/Navbar"
import Footer from "@/main_apps/components/globals/footers/Footer"

const poppins = Poppins({
    weight: '400',
    subsets: ['latin'],
});

export const meradata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}){
    return (
        <html lang="en">
            <body className={poppins.className}>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}